

create table scores (
  id bigint generated by default as identity primary key,
  match_name text not null,
  team_a integer default 0,
  team_b integer default 0,
  updated_at timestamp default now()
);



-- Table for polls
create table polls (
  id bigint generated by default as identity primary key,
  question text not null,
  created_at timestamp default now()
);

-- Table for poll options
create table poll_options (
  id bigint generated by default as identity primary key,
  poll_id bigint references polls(id) on delete cascade,
  option_text text not null,
  votes integer default 0
);

-- Insert sample poll
insert into polls (question) values ('Which frontend framework do you prefer?');

-- Insert options
insert into poll_options (poll_id, option_text) values
  (1, 'React'),
  (1, 'Solid.js'),
  (1, 'Svelte'),
  (1, 'Vue');
